services:
  backend:
    build: ./backend
    container_name: langchain-backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchainpw
      - POSTGRES_DB=langchain_db
      - VLLM_API_BASE=http://192.168.1.193:8090/v1
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchainpw
      POSTGRES_DB: langchain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
